### PR TITLE
CLI script to locally view odml files via webbrowser

### PR DESCRIPTION
**Pull request by mpsonntag**
Currently most web browsers no longer support viewing local files, that include further local files; see [here](https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Same-origin_policy_for_file:_URIs) for additional details.

odML XML files can be nicely rendered by stylesheets, but with the changes described above, this no longer works as smoothly as it did before on a local machine.

This PR therefore introduces another CLI script, `odmlview`, that starts up a local webserver. This webserver is able to properly serve odML XML files from a local directory and render them correctly, if the appropriate stylesheets are present in the same directory.

The CLI script provides an option (`--fetch`) to download the most commonly used xsl stylesheet, `odmlTerms.xsl` from `https://templates.g-node.org/_resources` to the local directory, to make sure that no stylesheet has to be shipped with python-odml, but potential users have easy access to it:

```
odmlview sets up a minimal webserver to view odml files saved in the
XML format via the webbrowser. After it started, the webserver will
open a new tab in the default webbrowser and display the content of
the directory the server was started from. odML files can then be
viewed from there.
To properly render XML, an odML file may contain the element
'<?xml-stylesheet  type="text/xsl" href="odmlTerms.xsl"?>' where the
'odmlTerms.xsl' stylesheet should reside in the same directory as the
odML file to be rendered. By using the '--fetch' flag the latest version
of this stylesheet will be downloaded from 'templates.g-node.org' to
the current directory when starting up the service.

Usage: odmlview [-p PORT] [--fetch]

Options:
    -p PORT         Port the server will use. Default: 8000
    --fetch         Fetch latest stylesheet from templates.g-node.org
                    to current directory
    -h --help       Show this screen
    --version       Show version
```

### CODE REVIEW

**Comment by JuliaSprenger** [comment]
When interrupting the odmlview, the port is still blocked and no other instance can be intiated. Is there a way to close odmlview properly? The error when attempting to run odmlview the second time is `OSError: [Errno 98] Address already in use`.

**Comment by JuliaSprenger** [comment]
Besides the port issue, the viewer works nicely :) Thanks!

**Comment by mpsonntag** [comment]
> When interrupting the odmlview, the port is still blocked and no other instance can be intiated. Is there a way to close odmlview properly? The error when attempting to run odmlview the second time is `OSError: [Errno 98] Address already in use`.

Hm, I'm using a proper shutdown command, this should not happen... I'll look into it!

**Comment by achilleas-k** [comment]
I'm getting the same.  It does shutdown, but it takes a minute.

Try `httpd.shutdown()`?
https://docs.python.org/3/library/socketserver.html#socketserver.BaseServer.shutdown

**Comment by JuliaSprenger** [comment]
It's maybe a bit counter intuitive, that `fetch` is fetching the style sheet AND starting an instance. I would have expected only the first to happen. 

Also I think `fetch` is downloading the style sheet for odml file format specification 1.0 and not 1.1, even though it should fetch the latest one.

**Comment by achilleas-k** [comment]
I wonder if it would be more appropriate for the scripts to be outside the odml module.  Since we don't expect them to be imported from anywhere they don't need to be a module or in the odml library itself.  Would it work if they were under `scripts/` at the root of the repo or would the setup script not be able to install them then?

**Comment by mpsonntag** [comment]
> I wonder if it would be more appropriate for the scripts to be outside the odml module. Since we don't expect them to be imported from anywhere they don't need to be a module or in the odml library itself. Would it work if they were under `scripts/` at the root of the repo or would the setup script not be able to install them then?

Please put this in its own issue since we already have a couple of other scripts.

**Comment by mpsonntag** [comment]
> It's maybe a bit counter intuitive, that `fetch` is fetching the style sheet AND starting an instance. I would have expected only the first to happen. This is especially confusing when having odml files sorted in multiple folders and running odmlview on the top level folder.
> 
> Also I think `fetch` is downloading the style sheet for odml file format specification 1.0 and not 1.1, even though it should fetch the latest one.

We actually serve up the latest version of the `odmlTerms.xsl`. If we need more specific updates for 1.1 we need to address these on the [templates](https://github.com/G-Node/odml-templates) and [terminologies](https://github.com/G-Node/odml-terminologies) repos.

**Comment by mpsonntag** [comment]
> When interrupting the odmlview, the port is still blocked and no other instance can be intiated. Is there a way to close odmlview properly? The error when attempting to run odmlview the second time is `OSError: [Errno 98] Address already in use`.

Should be resolved now.

**Pull request merged**
