### PR TITLE
Fix parsing of string values which include ","

### PR DESCRIPTION
**Pull request by JuliaSprenger**

### CODE REVIEW

**Comment by achilleas-k** [comment]
I've requested a review from @jgrewe on this since he wrote the relevant code.

**Comment by JuliaSprenger** [comment]
Thanks! This would help since I started looking into this again, but it is not obvious to me at which point the xml parser needs to be adapted to fix this.

**Comment by jgrewe** [comment]
I played around with the parser and the issue is related to the added lines 45, 46 in xmlparser.py, if I remove them the tests pass.
When wrapping the value content in a list (line 46), the csv reader apparently wraps the whole string in additional quotation marks. 
Is there a test case, or could you describe where the previous version failed?

**Comment by JuliaSprenger** [comment]
I had another look into it and think the original issue is rather related to the version converter.
With the file format version 1.1 values are stored including additional quotation marks, but for format version 1.0 this is not the case. These quotation marks are not added when converting from version 1.0 to 1.1 using the `odml.tools.version_converter`. The resulting lines in the odml file looking like this `<value>first, second, third</value`> are then interpreted as multiple values when being loaded using odml 1.4.

**Comment by JuliaSprenger** [comment]
I will close this issue, since the issue needs to be fixed in the version converter and not in the xmlparser.
The new issue is https://github.com/G-Node/python-odml/issues/295

**Pull request closed without merging**
