### PR TITLE
Review request: Appending arbitrary number of Sections/Properties in one go.

### PR DESCRIPTION
**Pull request by msuzen**
This is a working prototype for appending multiple `Sections` and `Properties` in one call. For example

```python
jordan_odml.mappend(
                    section_bulls, 
                    section_nc, 
                    section_ww, 
                    prop1,
                    prop2
                   )
```
`odml.doc.BaseDocument` and `odml.section.BaseSection` have been extended handling multiple appends via `mappend` method.

### CODE REVIEW

**Comment by lzehl** [comment]
@msuzen: I have a question regarding the BaseDocument extension:
So far Documents only append Sections not Properties. 
Did this change or is it just a misunderstanding in your description of your extension?

Btw: I'm really fond of the mappend possibility :) Thanks!

Best Lyuba

**Comment by msuzen** [comment]
@lzehl `mappend` extension do not change or interact with the `append` behaviour. So answer to your question is that, nothing has changed regarding `append`'s behaviour in `mappend`. Do you have an example in mind?

I am new to odML but as far as I can see one can append property to a Document in odML. Here is one example:

```python
import odml
import datetime as dt
jordan = odml.Document(
                                author="Michael Jordan",
                                date=dt.date(1991,9,1),
                                version=0.01
                      )
prop1 = odml.Property(
                               name="Coach",
                               value="Phil Jackson",
                               definition="Run the team."
                    )
jordan.append(prop1)
js=jordan.sections[0]
js.name, js.definition
```

PS: Thanks. `mappend` name is inspired from [mapply](https://stat.ethz.ch/R-manual/R-devel/library/base/html/mapply.html) from R.

**Comment by msuzen** [comment]
Please also note, `mappend` will be available via `mdoc.mdoc` and `msec.msec`. See tests, [here](https://github.com/msuzen/python-odml/blob/master/test/test_mdoc.py) and [here](https://github.com/msuzen/python-odml/blob/master/test/test_msec.py) for examples. I didn't want to alter base classes.

**Comment by lzehl** [comment]
Hi @msuzen!

Thanks for the quick reply!

For the Document/Property issue: 
No so far Properties could not be appended to a Document. At least not in a correct way.
In your example, although the Property is appended to the Document it is, as you also show, only retrievable via jordan.sections[0] and NOT via jordan.properties[0] which would be the correct call and was not implemented for Documents, because, as far as I know, a Document was not intended to contain Properties. From my point of view, it also makes sense that the Document as root section does not have Properties. But, I guess, that should be discussed then.

For the mappend vs append:
I like the idea of being able to append multiple Section objects to the Document and multiple Section and Property objects to a Section. But I would prefer having one function for this and not two. I would prefer having one function called 'append' which can either handle one object, or a list of objects. But, I guess, this is also a point to discuss then.

Best Lyuba

**Comment by msuzen** [comment]
@lzehl Thanks for the detailed response.  I think both of your comments are open to discussion.

I agree, regarding properties on the Document object, if it isn't allowed to append a property, `odML` should throw an exception if a property is attempted to append to Document object, in the first place, created an issue [#69](https://github.com/G-Node/python-odml/issues/69)

**Comment by jgrewe** [comment]
as @lzehl mentioned, the document is not supposed to contain properties and it should stay like this. 

I like the way to add multiple children at the same time, though I would prefer the method(s) at the already existing classes

**Comment by msuzen** [comment]
@lzehl @jgrewe Thank you for the review. I will do another pull adding the functionality into an existing method, along with resolving [issue #69](https://github.com/G-Node/python-odml/issues/69)

**Pull request closed without merging**
