### PR TITLE
removed redundant file

### PR DESCRIPTION
**Pull request by Vutsuak16**
the example file had link to a repo.
It was not being used anywhere so I thought better to remove it :D

### CODE REVIEW

**Comment by lzehl** [comment]
Hello @Vutsuak16, thanks for your correction, but this is a change which is covered by the update of the tutorial/docu I'm currently working on (e.g. #58). The repo link is also not redundant, but the functionality of the repository attribute was not yet integrated into the tutorial. It will be, though, with the new changes of odML. In preparing a tutorial part for this, I actually also noticed some issues with the repository attribute. It would be great if someone could check on this. Should I make an issue with a description for this for you?
Best Lyuba

**Comment by Vutsuak16** [comment]
@lzehl  Sure. 
I would be glad to work on it :)

**Comment by lzehl** [comment]
Great :) give me a bit to wrap up the problems/issues I see with the functionality of repository

**Comment by lzehl** [comment]
@Vutsuak16: I created an issue (#74) for the repository stuff... let me know if you have questions.

**Comment by lzehl** [comment]
and if you and everyone agrees, we could close this issue and not merge your changes into the master branch since it will be covered by #58 and #74

**Comment by Vutsuak16** [comment]
@lzehl  sure we can close the issue now :) Meanwhile I work on the issue which you created

**Comment by achilleas-k** [comment]
Closing PR.

**Pull request closed without merging**
